remote_theme: pages-themes/slate@v0.2.0
title: STAT228 Portfolio
author: Tessa Volpe
description: 
    This portfolio showcases my growing experience through my participation in the Statistics 228 course, Introduction to Data Science
